[package]
name = "spaceman-dmm"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[[bin]]
name = "editor"
path = "src/editor/main.rs"

[dependencies]
same-file = "1.0.0"
toml = "0.4.5"
serde = "1.0.21"
serde_derive = "1.0.21"
dreammaker = { path = "src/dreammaker" }
dmm-tools = { path = "src/tools" }
qt-extras = { path = "src/qt-extras" }

[dependencies.glium]
default-features = false
version = "0.18.1"

[profile.dev]
opt-level = 3

[profile.release]
lto = true

[workspace]
members = ["src/cli", "src/langserver"]
