[workspace]
members = [
    "src/cli",
    "src/dmdoc",
    "src/dreammaker",
    "src/editor",
    #"src/editor-qt",
    "src/interval-tree",
    "src/langserver",
    #"src/qt-extras",
    "src/tools",
]

[profile.dev]
opt-level = 2

[profile.release]
lto = true
