[package]
name = "minimap"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[dependencies]
xml-rs = "0.7.0"
petgraph = { version = "0.4.9", default-features = false }
png = "0.11.0"
inflate = "0.3.3"
ndarray = "0.10.11"
rand = "0.3.17"
linked-hash-map = "0.5.0"
flame = { version = "0.2.0", optional = true }

[dev-dependencies]
walkdir = "2.0.1"

[profile.dev]
opt-level = 3
