[package]
name = "spaceman-dmm"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[[bin]]
name = "editor"
path = "src/editor/main.rs"

[dependencies]
conrod = { version = "0.56.0", features = ["glium", "winit"] }
dreammaker = { path = "src/dreammaker" }
dmm-tools = { path = "src/tools" }

[profile.dev]
opt-level = 3

[profile.release]
lto = true

[workspace]
