[package]
name = "dmdoc"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[[bin]]
name = "dmdoc"
path = "main.rs"

[dependencies]
dreammaker = { path = "../dreammaker" }
docstrings = "0.1.1"

[dev-dependencies]
walkdir = "2.0.1"
