[package]
name = "spaceman-dmm"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[[bin]]
name = "editor"
path = "main.rs"

[dependencies]
dreammaker = { path = "../dreammaker" }
#dmm-tools = { path = "../tools" }
glium = "0.22.0"
imgui = "0.0.20"
imgui-glium-renderer = "0.0.20"
