[package]
name = "dmm-tools"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[lib]
path = "lib.rs"

[dependencies]
png = "0.11.0"
inflate = "0.3.3"
ndarray = "0.10.11"
rand = "0.3.17"
linked-hash-map = "0.5.0"
flame = { version = "0.2.0", optional = true }
dreammaker = { path = "../dreammaker" }

[dev-dependencies]
walkdir = "2.0.1"
